#Rent multiplier 
#x2 complete set
#mortgage value = price/2

class Properties():

    def __init__(self):
        self.names = {
            "Mediterranean Ave": {
                "price": 60,
                "mortgaged": False,
                "base_rent": 2,
                "one_house_cost": 10,
                "two_house_cost": 30,
                "three_house_cost": 90,
                "four_house_cost": 160,
                "hotel_cost": 250,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "brown",
                "house_build_cost": 50,
                "owner": None
            },
            "Baltic Ave": {
                "price": 60,
                "mortgaged": False,
                "base_rent": 4,
                "one_house_cost": 20,
                "two_house_cost": 60,
                "three_house_cost": 180,
                "four_house_cost": 320,
                "hotel_cost": 450,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "brown",
                "house_build_cost": 50,
                "owner": None
            },
            "Oriental Ave": {
                "price": 100,
                "mortgaged": False,
                "base_rent": 6,
                "one_house_cost": 30,
                "two_house_cost": 90,
                "three_house_cost": 270,
                "four_house_cost": 400,
                "hotel_cost": 550,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "turquoise",
                "house_build_cost": 50,
                "owner": None
            },
            "Vermont Ave": {
                "price": 100,
                "mortgaged": False,
                "base_rent": 6,
                "one_house_cost": 30,
                "two_house_cost": 90,
                "three_house_cost": 270,
                "four_house_cost": 400,
                "hotel_cost": 550,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "turquoise",
                "house_build_cost": 50,
                "owner": None
            },
            "Connecticut Ave": {
                "price": 120,
                "mortgaged": False,
                "base_rent": 8,
                "one_house_cost": 40,
                "two_house_cost": 100,
                "three_house_cost": 300,
                "four_house_cost": 450,
                "hotel_cost": 600,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "turquoise",
                "house_build_cost": 50,
                "owner": None
            },
            "St Charles Pl": {
                "price": 140,
                "mortgaged": False,
                "base_rent": 10,
                "one_house_cost": 50,
                "two_house_cost": 150,
                "three_house_cost": 450,
                "four_house_cost": 625,
                "hotel_cost": 750,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "maroon",
                "house_build_cost": 100,
                "owner": None
            },
            "States Ave": {
                "price": 140,
                "mortgaged": False,
                "base_rent": 10,
                "one_house_cost": 50,
                "two_house_cost": 150,
                "three_house_cost": 450,
                "four_house_cost": 625,
                "hotel_cost": 750,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "maroon",
                "house_build_cost": 100,
                "owner": None
            },
            "Virginia Ave": {
                "price": 160,
                "mortgaged": False,
                "base_rent": 12,
                "one_house_cost": 60,
                "two_house_cost": 180,
                "three_house_cost": 500,
                "four_house_cost": 700,
                "hotel_cost": 900,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "maroon",
                "house_build_cost": 100,
                "owner": None
            },
            "St James Pl": {
                "price": 180,
                "mortgaged": False,
                "base_rent": 14,
                "one_house_cost": 70,
                "two_house_cost": 200,
                "three_house_cost": 550,
                "four_house_cost": 750,
                "hotel_cost": 950,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "orange",
                "house_build_cost": 100,
                "owner": None
            },
            "Tennessee Ave": {
                "price": 180,
                "mortgaged": False,
                "base_rent": 14,
                "one_house_cost": 70,
                "two_house_cost": 200,
                "three_house_cost": 550,
                "four_house_cost": 750,
                "hotel_cost": 950,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "orange",
                "house_build_cost": 100,
                "owner": None
            },
            "New York Ave": {
                "price": 200,
                "mortgaged": False,
                "base_rent": 16,
                "one_house_cost": 80,
                "two_house_cost": 220,
                "three_house_cost": 600,
                "four_house_cost": 800,
                "hotel_cost": 1000,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "orange",
                "house_build_cost": 100,
                "owner": None
            },
            "Kentucky Ave": {
                "price": 220,
                "mortgaged": False,
                "base_rent": 18,
                "one_house_cost": 90,
                "two_house_cost": 250,
                "three_house_cost": 700,
                "four_house_cost": 875,
                "hotel_cost": 1050,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "red",
                "house_build_cost": 150,
                "owner": None
            },
            "Indiana Ave": {
                "price": 220,
                "mortgaged": False,
                "base_rent": 18,
                "one_house_cost": 90,
                "two_house_cost": 250,
                "three_house_cost": 700,
                "four_house_cost": 875,
                "hotel_cost": 1050,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "red",
                "house_build_cost": 150,
                "owner": None
            },
            "Illinois Ave": {
                "price": 240,
                "mortgaged": False,
                "base_rent": 20,
                "one_house_cost": 100,
                "two_house_cost": 300,
                "three_house_cost": 750,
                "four_house_cost": 925,
                "hotel_cost": 1100,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "red",
                "house_build_cost": 150,
                "owner": None
            },
            "Atlantic Ave": {
                "price": 260,
                "mortgaged": False,
                "base_rent": 22,
                "one_house_cost": 110,
                "two_house_cost": 330,
                "three_house_cost": 800,
                "four_house_cost": 975,
                "hotel_cost": 1150,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "yellow",
                "house_build_cost": 150,
                "owner": None
            },
            "Ventnor Ave": {
                "price": 260,
                "mortgaged": False,
                "base_rent": 22,
                "one_house_cost": 110,
                "two_house_cost": 330,
                "three_house_cost": 800,
                "four_house_cost": 975,
                "hotel_cost": 1150,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "yellow",
                "house_build_cost": 150,
                "owner": None
            },
            "Marvin Gardens": {
                "price": 280,
                "mortgaged": False,
                "base_rent": 24,
                "one_house_cost": 120,
                "two_house_cost": 360,
                "three_house_cost": 850,
                "four_house_cost": 1025,
                "hotel_cost": 1200,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "yellow",
                "house_build_cost": 150,
                "owner": None
            },
            "Pacific Ave": {
                "price": 300,
                "mortgaged": False,
                "base_rent": 26,
                "one_house_cost": 130,
                "two_house_cost": 390,
                "three_house_cost": 900,
                "four_house_cost": 1100,
                "hotel_cost": 1275,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "green",
                "house_build_cost": 200,
                "owner": None
            },
            "N Carolina Ave": {
                "price": 300,
                "mortgaged": False,
                "base_rent": 26,
                "one_house_cost": 130,
                "two_house_cost": 390,
                "three_house_cost": 900,
                "four_house_cost": 1100,
                "hotel_cost": 1275,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "green",
                "house_build_cost": 200,
                "owner": None
            },
            "Penn Ave": {
                "price": 320,
                "mortgaged": False,
                "base_rent": 28,
                "one_house_cost": 150,
                "two_house_cost": 450,
                "three_house_cost": 1000,
                "four_house_cost": 1200,
                "hotel_cost": 1400,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "green",
                "house_build_cost": 200,
                "owner": None
            },
            "Park Pl": {
                "price": 350,
                "mortgaged": False,
                "base_rent": 35,
                "one_house_cost": 175,
                "two_house_cost": 500,
                "three_house_cost": 1100,
                "four_house_cost": 1300,
                "hotel_cost": 1500,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "blue",
                "house_build_cost": 200,
                "owner": None
            },
            "Boardwalk": {
                "price": 400,
                "mortgaged": False,
                "base_rent": 50,
                "one_house_cost": 200,
                "two_house_cost": 600,
                "three_house_cost": 1400,
                "four_house_cost": 1700,
                "hotel_cost": 2000,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "blue",
                "house_build_cost": 200,
                "owner": None
            },
            "Reading Railroad": {
                "price": 200,
                "mortgaged": False,
                "base_rent": 25,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "railroad",
                "house_build_cost": None,
                "owner": None
            },
            "Penn Railroad": {
                "price": 200,
                "mortgaged": False,
                "base_rent": 25,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "railroad",
                "house_build_cost": None,
                "owner": None
            },
            "B&O Railroad": {
                "price": 200,
                "mortgaged": False,
                "base_rent": 25,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "railroad",
                "house_build_cost": None,
                "owner": None
            },
            "Short Line Railroad": {
                "price": 200,
                "mortgaged": False,
                "base_rent": 25,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "railroad",
                "house_build_cost": None,
                "owner": None
            },
            "Electric Co": {
                "price": 150,
                "mortgaged": False,
                "base_rent": None,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "utility",
                "house_build_cost": None,
                "owner": None
            },
            "Water Works": {
                "price": 150,
                "mortgaged": False,
                "base_rent": None,
                "one_house_cost": None,
                "two_house_cost": None,
                "three_house_cost": None,
                "four_house_cost": None,
                "hotel_cost": None,
                "num_houses": 0,
                "num_hotels": 0,
                "type": "utility",
                "house_build_cost": None,
                "owner": None
            },
        }